# src/main/resources/application.properties
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mvc

# Hibernate crea/actualiza las tablas automáticamente
quarkus.hibernate-orm.database.generation=update