# Conexión a la base de datos
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mvc
quarkus.hibernate-orm.database.generation=update

# 1. Desactivar el chequeo estricto de versión de XAMPP/MariaDB
quarkus.hibernate-orm.database.version-check.enabled=false

# 2. Cambiar el puerto para evitar el error "Address already in use"
quarkus.http.port=8081